apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-feed-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-feed
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
