apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-feed-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-feed
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
