apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-user
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
