apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-reverseproxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-reverseproxy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
