name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UDAGRAM_API_FEED_IMAGE_NAME=udagram-api-feed
      UDAGRAM_API_USER_IMAGE_NAME=udagram-api-user
      UDAGRAM_FRONTEND_IMAGE_NAME=udagram-frontend
      UDAGRAM_REVERSEPROXY_IMAGE_NAME=reverseproxy
      TAG=v1  # Change this to the appropriate tag for the master branch

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: 
          docker-compose -f docker-compose-build.yaml build --parallel --no-cache
          docker push $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG