name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: tuanvipandpro
      UDAGRAM_API_FEED_IMAGE_NAME: udagram-api-feed
      UDAGRAM_API_USER_IMAGE_NAME: udagram-api-user
      UDAGRAM_FRONTEND_IMAGE_NAME: udagram-frontend
      UDAGRAM_REVERSEPROXY_IMAGE_NAME: reverseproxy
      TAG: v4  # Change this to the appropriate tag for the master branch

    steps:
      - uses: actions/checkout@v3

      - name: Check Docker Status
        run: docker version

      - name: Start Docker Service (if necessary)
        run: sudo systemctl start docker

      - name: Install Docker-Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Check Docker-Compose Version
        run: docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: 
          docker-compose -f ./docker-compose-build.yaml build --parallel --no-cache

      - name: Tag Docker Images
        run: |
          docker tag $UDAGRAM_API_FEED_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
          docker tag $UDAGRAM_API_USER_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
          docker tag $UDAGRAM_FRONTEND_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
          docker tag $UDAGRAM_REVERSEPROXY_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG

      - name: Push Docker Images
        run: |
          docker push $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
          docker push $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG